package com.example.backend.Models;

public enum EReportReason {
    BREAKS_RULES, HARASSMENT, HATE, SHARING_PERSONAL_INFO, IMPERSONATION, COPYRIGHT_VIOLATION, TRADEMARK_VIOLATION, SELF_HARM_OR_SUICIDE, OTHER
}
