package Models;

public enum ReportReason {
    BREAKS_RULES, HARRASMENT, HATE, SHARING_PERSONAL_INFORMATION, IMPERSONATION, COPYRIGHT_VIOLATION, TRADEMARK_VIOLATION, SPAM, SELF_HARM_OR_SUICIDE, OTHER
}
